theme: minima
title: 这是一个没有内容的博客
author: GitHub用户
email: 13489600286@163.com
description: > # this means to ignore newlines until "baseurl:"
  课程需要，无内容
# social links
github_username:  sfmmdm # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
